opt_in_rules: # opt-in rules
  - empty_count
  - empty_string
  - force_unwrapping
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discarded_notification_center_observer
  - explicit_init
  - first_where
  - last_where
  - implicit_return
  - reduce_into
  - unneeded_parentheses_in_closure_argument
  - unused_enumerated
  - unused_import
  - vertical_parameter_alignment
  - vertical_whitespace_closing_braces
